#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/config/xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

# export STATUSBAR="i3blocks" # Uncomment this line when using i3.

# . ~/.xprofile
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
lxsession &
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
picom &			# xcompmgr for transparency
~/.config/polybar/launch.sh &
dunst &			# dunst for notifications
sxhkd &
unclutter &		# Remove mouse when idle
xrdb -load ~/.config/X11/xresources
# Your default LARBS WM is determined in your `~/.profile` on login.  Here we
# run the proper command to run when the graphical environment starts.

# Comment/uncomment these lines depending on what wm you want to use. Also
# check the i3blocks line above
exec bspwm
# ssh-agent i3
